"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const read = (file) => fs.readFileSync(path.join(__dirname, "..", file), "utf8");
const content = read("content/content.js");
const tools = read("tools/content.js");
const css = read("content/content.css");
const manifest = JSON.parse(read("manifest.json"));
assert.equal(((content + tools).match(/setInterval\(/g) || []).length, 1);
assert.match(content, /window\.dispatchEvent\(new Event\(routeChangeEventName\)\)/);
assert.match(content, /window\.navigation\?\.addEventListener\("navigate"/);
for (const event of ["popstate", "hashchange", "pageshow"]) assert.ok(content.includes(`addEventListener("${event}"`));
assert.doesNotMatch(tools, /setInterval\(/);
assert.doesNotMatch(content, /MutationObserver|querySelectorAll|createElement|applySelectedTheme/);
assert.doesNotMatch(css, /background:|border:|color:|data-gpttoolkit-theme/);
assert.match(css, /data-gpttoolkit-font-text/);
assert.match(css, /role="math"/);
assert.match(css, /\.katex/);
assert.deepEqual(manifest.content_scripts[0].js, ["shared/fonts.js", "content/content.js"]);
assert.equal(manifest.name, "GPT Toolkit");
assert.equal(fs.existsSync(path.join(__dirname, "..", "shared/themes.js")), false);
assert.doesNotMatch(read("popup/popup.html"), /theme-panel|data-style-mode="theme"/);
assert.doesNotMatch(read("tools/content.css"), /var\(--gpttoolkit-(?:text|surface|border|hover)/);
console.log("Checked font-only runtime and shared route lifecycle contracts.");
